version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maths_challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: quiz_app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:password@db/maths_challenge
    volumes:
      - .:/app

volumes:
  postgres_data:
