"""Update database

Revision ID: 2a384c90567a
Revises: fc0001d95ce1
Create Date: 2025-03-06 19:05:34.146830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a384c90567a'
down_revision = 'fc0001d95ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=10), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_session.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz_responses')
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('quiz_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quiz_responses_pkey')
    )
    op.drop_table('quiz_response')
    # ### end Alembic commands ###
