"""Modified the structure

Revision ID: bcad0ac72b15
Revises: 
Create Date: 2025-03-06 13:12:12.659861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcad0ac72b15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_session')
    op.drop_table('quiz_responses')
    op.drop_table('uploaded_file')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('option_b', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('option_c', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('option_d', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('option_e', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_pkey')
    )
    op.create_table('uploaded_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='uploaded_file_pkey')
    )
    op.create_table('quiz_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quiz_responses_pkey')
    )
    op.create_table('quiz_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('question_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quiz_session_pkey'),
    sa.UniqueConstraint('session_id', name='quiz_session_session_id_key')
    )
    # ### end Alembic commands ###
